spring.application.name=epi
spring.datasource.url=jdbc:postgresql://localhost:5432/gestion_epi
spring.datasource.username=userepi
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=update
server.port=8082
spring.main.allow-bean-definition-overriding=true